<?php
/*uptime:2012-10-27 12:49:58*/
$document_21=array (
  'did' => '21',
  'lng' => 'cn',
  'pid' => '50',
  'mid' => '1',
  'aid' => '1',
  'tid' => '10',
  'extid' => '0',
  'sid' => '0',
  'fgid' => '0',
  'linkdid' => '',
  'isclass' => '1',
  'islink' => '0',
  'ishtml' => '1',
  'ismess' => '1',
  'isorder' => '0',
  'ktid' => '0',
  'purview' => '0',
  'istemplates' => '0',
  'isbase' => '0',
  'recommend' => '',
  'tsn' => 'SN20120608154152905',
  'title' => '戴尔将与VMware合作推出云基础设施服务',
  'longtitle' => '',
  'color' => '',
  'author' => '',
  'source' => '',
  'pic' => '',
  'tags' => '',
  'keywords' => '',
  'description' => ' 北京时间8月30日早间消息，戴尔将在今年晚些时候与VMware合作推出第一项云基础设施服务，继续将其业务向PC以外的领域拓展，进入利润率更高的软',
  'summary' => '',
  'link' => '',
  'oprice' => '0.00',
  'bprice' => '0.00',
  'click' => '3',
  'addtime' => '1314711837',
  'uptime' => '1339141312',
  'template' => 'article_read',
  'filename' => '21',
  'filepath' => 'news/media',
  'filepage' => '2',
);
?>