<?php
/*uptime:2012-10-27 12:18:06*/
$document_8_all=array (
  'datid' => NULL,
  'did' => '8',
  'downloadurl' => NULL,
  'jobnum' => NULL,
  'dcid' => '7',
  'content' => '&lt;div style=&quot;text-align: center;&quot;&gt;&lt;iframe src=&quot;http://maps.google.com/maps?f=d&amp;amp;source=s_d&amp;amp;saddr=&amp;amp;daddr=&amp;amp;hl=zh-CN&amp;amp;geocode=&amp;amp;mra=mr&amp;amp;doflg=ptk&amp;amp;sll=23.825551,114.587402&amp;amp;sspn=13.082321,35.15625&amp;amp;ie=UTF8&amp;amp;ll=22.523617,114.062805&amp;amp;spn=0.019821,0.027938&amp;amp;z=15&amp;amp;vpsrc=6&amp;amp;output=embed&quot; width=&quot;620&quot; height=&quot;500&quot; scrolling=&quot;no&quot; marginwidth=&quot;0&quot; marginheight=&quot;0&quot; frameborder=&quot;0&quot;&gt;&lt;/iframe&gt;&lt;/div&gt;',
  'lng' => 'cn',
  'pid' => '50',
  'mid' => '8',
  'aid' => '1',
  'tid' => '21',
  'extid' => '0',
  'sid' => '0',
  'fgid' => '0',
  'linkdid' => '',
  'isclass' => '1',
  'islink' => '0',
  'ishtml' => '1',
  'ismess' => '0',
  'isorder' => '0',
  'ktid' => '0',
  'purview' => '0',
  'istemplates' => '0',
  'isbase' => '1',
  'recommend' => '',
  'tsn' => 'SN20110830211533328',
  'title' => '地图指示',
  'longtitle' => '地图指示',
  'color' => '',
  'author' => '',
  'source' => '',
  'pic' => '',
  'tags' => '',
  'keywords' => '',
  'description' => '',
  'summary' => '',
  'link' => '',
  'oprice' => '0.00',
  'bprice' => '0.00',
  'click' => '0',
  'addtime' => '1314706903',
  'uptime' => '1314710133',
  'template' => 'base_read',
  'filename' => '8',
  'filepath' => 'contact-us/map',
  'filepage' => '1',
);
?>