<?php
/*uptime:2012-10-27 12:14:29*/
$model_array_cn_0_0_0_0=array (
  0 => 
  array (
    'mid' => '1',
    'lng' => 'cn',
    'modelname' => '新闻',
    'pagemax' => '10',
    'pagesylte' => '1',
    'isclass' => '1',
    'lockin' => '1',
    'isbase' => '0',
    'istsn' => '0',
    'isalbum' => '0',
    'isextid' => '1',
    'issid' => '0',
    'isfgid' => '1',
    'islinkdid' => '1',
    'isorder' => '0',
    'ismessage' => '1',
    'ispurview' => '1',
    'addtime' => '0',
  ),
  1 => 
  array (
    'mid' => '3',
    'lng' => 'cn',
    'modelname' => '产品',
    'pagemax' => '20',
    'pagesylte' => '1',
    'isclass' => '1',
    'lockin' => '1',
    'isbase' => '0',
    'istsn' => '1',
    'isalbum' => '1',
    'isextid' => '1',
    'issid' => '1',
    'isfgid' => '0',
    'islinkdid' => '1',
    'isorder' => '1',
    'ismessage' => '1',
    'ispurview' => '1',
    'addtime' => '1280603581',
  ),
  2 => 
  array (
    'mid' => '4',
    'lng' => 'cn',
    'modelname' => '下载',
    'pagemax' => '20',
    'pagesylte' => '1',
    'isclass' => '1',
    'lockin' => '0',
    'isbase' => '0',
    'istsn' => '0',
    'isalbum' => '0',
    'isextid' => '1',
    'issid' => '0',
    'isfgid' => '0',
    'islinkdid' => '1',
    'isorder' => '0',
    'ismessage' => '0',
    'ispurview' => '1',
    'addtime' => '0',
  ),
  3 => 
  array (
    'mid' => '7',
    'lng' => 'cn',
    'modelname' => '招聘',
    'pagemax' => '20',
    'pagesylte' => '1',
    'isclass' => '1',
    'lockin' => '0',
    'isbase' => '0',
    'istsn' => '0',
    'isalbum' => '0',
    'isextid' => '0',
    'issid' => '0',
    'isfgid' => '1',
    'islinkdid' => '0',
    'isorder' => '0',
    'ismessage' => '0',
    'ispurview' => '1',
    'addtime' => '1280603581',
  ),
);
?>