<?php
/*uptime:2012-10-27 12:14:34*/
$modeatt_array_add_8_=array (
  0 => 
  array (
    'aid' => '127',
    'pid' => '1',
    'mid' => '8',
    'typename' => '标题',
    'typeremark' => '标题长度不能大于200个任意字符',
    'attrname' => 'title',
    'inputtype' => 'string',
    'attrvalue' => '',
    'attrsize' => '80',
    'attrrow' => '5',
    'attrlenther' => '200',
    'isvalidate' => '1',
    'validatetext' => '',
    'isclass' => '1',
    'issearch' => '0',
    'lockin' => '1',
    'islockin' => '1',
    'issys' => '1',
  ),
  1 => 
  array (
    'aid' => '125',
    'pid' => '2',
    'mid' => '8',
    'typename' => '简介',
    'typeremark' => '',
    'attrname' => 'summary',
    'inputtype' => 'htmltext',
    'attrvalue' => '',
    'attrsize' => '99',
    'attrrow' => '80',
    'attrlenther' => '50',
    'isvalidate' => '0',
    'validatetext' => '',
    'isclass' => '1',
    'issearch' => '0',
    'lockin' => '1',
    'islockin' => '1',
    'issys' => '6',
  ),
  2 => 
  array (
    'aid' => '126',
    'pid' => '3',
    'mid' => '8',
    'typename' => '代表图片',
    'typeremark' => '',
    'attrname' => 'pic',
    'inputtype' => 'img',
    'attrvalue' => '',
    'attrsize' => '50',
    'attrrow' => '5',
    'attrlenther' => '200',
    'isvalidate' => '0',
    'validatetext' => '',
    'isclass' => '1',
    'issearch' => '0',
    'lockin' => '1',
    'islockin' => '1',
    'issys' => '5',
  ),
  3 => 
  array (
    'aid' => '124',
    'pid' => '4',
    'mid' => '8',
    'typename' => '内容',
    'typeremark' => '',
    'attrname' => 'content',
    'inputtype' => 'editor',
    'attrvalue' => '',
    'attrsize' => '99',
    'attrrow' => '400',
    'attrlenther' => '50',
    'isvalidate' => '1',
    'validatetext' => '',
    'isclass' => '1',
    'issearch' => '0',
    'lockin' => '1',
    'islockin' => '1',
    'issys' => '7',
  ),
);
?>