<?php
/*uptime:2012-10-27 12:44:57*/
$typelist_view_21=array (
  'tid' => '21',
  'pid' => '50',
  'mid' => '8',
  'topid' => '8',
  'upid' => '8',
  'exmid' => '0',
  'linkid' => '8',
  'gotoid' => '0',
  'lng' => 'cn',
  'typename' => '地图指示',
  'content' => '',
  'keywords' => '',
  'description' => '',
  'typepic' => 'upfile/2011/08/20/20110820163814_156.jpg',
  'dirname' => 'map',
  'purview' => '0',
  'ismenu' => '0',
  'isaccessory' => '0',
  'isclass' => '1',
  'ispart' => '1',
  'styleid' => '4',
  'pageclass' => '1',
  'indextemplates' => 'article_index',
  'template' => 'article_list',
  'readtemplate' => 'base_read',
  'filenamestyle' => '{tid}_{pageid}',
  'readnamestyle' => '{did}',
  'isline' => '1',
  'gotoline' => '0',
  'typeurl' => 'http://',
  'dirpath' => 'contact-us',
  'iswap' => '1',
  'waptempalte' => 'article_list',
  'wapreadtemplate' => 'base_read',
  'pagemax' => '0',
  'addtime' => '1314706903',
  'isorderby' => '1',
  'ordertype' => '1',
);
?>