<?php
/*uptime:2012-10-27 12:43:15*/
$typelist_view_4=array (
  'tid' => '4',
  'pid' => '2',
  'mid' => '1',
  'topid' => '0',
  'upid' => '0',
  'exmid' => '0',
  'linkid' => '0',
  'gotoid' => '0',
  'lng' => 'cn',
  'typename' => '新闻资讯',
  'content' => '',
  'keywords' => '',
  'description' => '',
  'typepic' => 'upfile/2011/08/20/20110820163814_156.jpg',
  'dirname' => 'news',
  'purview' => '0',
  'ismenu' => '1',
  'isaccessory' => '1',
  'isclass' => '1',
  'ispart' => '1',
  'styleid' => '1',
  'pageclass' => '1',
  'indextemplates' => 'article_index',
  'template' => 'article_list',
  'readtemplate' => 'article_read',
  'filenamestyle' => '{tid}_{pageid}',
  'readnamestyle' => '{did}',
  'isline' => '1',
  'gotoline' => '0',
  'typeurl' => 'http://',
  'dirpath' => '',
  'iswap' => '1',
  'waptempalte' => 'article_list',
  'wapreadtemplate' => 'article_read',
  'pagemax' => '0',
  'addtime' => '1314706047',
  'isorderby' => '1',
  'ordertype' => '1',
);
?>