<?php
/*uptime:2012-10-27 12:43:11*/
$typelist_view_23=array (
  'tid' => '23',
  'pid' => '50',
  'mid' => '3',
  'topid' => '5',
  'upid' => '11',
  'exmid' => '0',
  'linkid' => '0',
  'gotoid' => '0',
  'lng' => 'cn',
  'typename' => '手机',
  'content' => '',
  'keywords' => '',
  'description' => '',
  'typepic' => 'upfile/2011/08/20/20110820163814_156.jpg',
  'dirname' => 'moblie',
  'purview' => '0',
  'ismenu' => '0',
  'isaccessory' => '0',
  'isclass' => '1',
  'ispart' => '1',
  'styleid' => '2',
  'pageclass' => '1',
  'indextemplates' => 'goods_index',
  'template' => 'goods_list',
  'readtemplate' => 'goods_read',
  'filenamestyle' => '{tid}_{pageid}',
  'readnamestyle' => '{did}',
  'isline' => '1',
  'gotoline' => '0',
  'typeurl' => 'http://',
  'dirpath' => 'goods',
  'iswap' => '1',
  'waptempalte' => 'goods_list',
  'wapreadtemplate' => 'goods_read',
  'pagemax' => '0',
  'addtime' => '1314712676',
  'isorderby' => '1',
  'ordertype' => '1',
);
?>